export const INFO_WEATHER = "INFO_WEATHER";
export const INFO_WEATHER_ERROR = "INFO_WEATHER_ERROR";
export const INFO_WEATHER_SUCCESS = "INFO_WEATHER_SUCCESS";
export const INFO_WEATHER_FEW_DAYS = "INFO_WEATHER_FEW_DAYS";
export const INFO_WEATHER_FEW_DAYS_ERROR = "INFO_WEATHER_FEW_DAYS_ERROR";
export const INFO_WEATHER_FEW_DAYS_SUCCESS = "INFO_WEATHER_FEW_DAYS_SUCCESS";
